### ISSUE TITLE
Is it possible to provide front-end code? 

### ISSUE THREAD

**Issue by Finedl** [JackKelly/JackKelly.github.io#2]
Is it possible to provide front-end code? 
For: https://my2050.beis.gov.uk/?levers=111111111111111 
I want to learn how to realize this. Please contact me, thank you.  
My email：cdlord@qq.com

**Comment by JackKelly** [comment]
Thanks for getting in touch. I didn't work on my2050, sorry, and I don't know who did work on it! Sorry to not be of more help :slightly_smiling_face:
